### ISSUE TITLE
Issue on mac

### ISSUE THREAD

**Issue by anurag2361** [encoredev/encore#1545]
Everytime i want to create an app on my mac machine, it starts the server, opens the frontend and then the server just throws and error and shuts down. This is the error it throws: 
 ```
✔ Building Encore application graph... Done!
  ✔ Analyzing service topology... Done!
  ✔ Starting Encore application... Done!

  Encore development server running!

  Your API is running at:     http://127.0.0.1:4000
  Development Dashboard URL:  http://127.0.0.1:9400/mqrmc

Error: dlopen(/opt/homebrew/Cellar/encore/1.43.8/libexec/runtimes/js/encore-runtime.node, 0x0001): tried: '/opt/homebrew/Cellar/encore/1.43.8/libexec/runtimes/js/encore-runtime.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/encore/1.43.8/libexec/runtimes/js/encore-runtime.node' (no such file), '/opt/homebrew/Cellar/encore/1.43.8/libexec/runtimes/js/encore-runtime.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/mymachine/example-encore/node_modules/encore.dev/dist/internal/runtime/napi/napi.cjs:11:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I have tried all templates, even the empty one. This happens on all of them. What is the issue here?

**Comment by corrosive4354** [comment]
If you are using a Mac with an M1 or M2 chip, this problem may occur because these chips use the ARM architecture, and some software or libraries are still compiled for Intel's x86_64 architecture.

Seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use than docker and homebrew on Mac, and supports one-click deployment of node.js

**Comment by jainkuniya** [comment]
I am also getting the same issue

**Comment by ekerfelt** [comment]
Are you running MacOS on arm64 or x86_64?

(you'll find it by running e.g. `uname -a` in a terminal)

**Comment by rapidsfirst** [comment]
I have the same issue and I have a Mac M1 laptop running encore run in iTerm with Rosetta checked so it’s running with x86_64. I’m guessing by your question that’s my issue on why I can’t get encore to run in the terminal. So do I have a install encore and reinstall with brew again with an unchecked Rosetta iTerm?

**Comment by kaufmann42** [comment]
+1 I guess we're just not supporting new macs. Seems like a big market to lose

**Comment by eandre** [comment]
Encore is perfectly well supported on macOS, both Apple Silicon (arm64) and Intel (x86_64). Almost everybody on the Encore development team uses an Apple Silicon MacBook, in fact. The issue here is when installing via Homebrew with Homebrew being set up incorrectly, i.e. using an x86_64 install of Homebrew on an Apple Silicon Mac. That leads to Homebrew installing the x86_64 version of Encore, which doesn't work when loading the native library.

**Comment by aekasitt** [comment]
This issue happened to me too when installing with Homebrew.
Even without specifying architecture, the file being downloaded is `encore-1.45.7-darwin_arm64.tar.gz`

```sh
brew install encoredev/tap/encore
```

But to be thorough, I uninstalled encore and reinstalled using the following commands

```sh
brew uninstall encoredev/tap/encore
arch -arm64 brew install encoredev/tap/encore
```

At no change. Still running into the above error. `ERR_DLOPEN_FAILED`

**Comment by fredr** [comment]
What are the output of the commands described here: https://github.com/orgs/Homebrew/discussions/3223#discussioncomment-2658471

is your homebrew installed with the correct arch?
