### ISSUE TITLE
Wrapping the context too many times causes panics

### ISSUE THREAD

**Issue by MatthewJamesBoyle** [encoredev/encore#31]
Consider the following code:

```
package hello

import (
	"context"
	"golang.org/x/sync/errgroup"
	"net/http"
)

type Response struct {
	Message string
}

//encore:api public
func World(ctx context.Context) (*Response, error) {

	eg, ctx := errgroup.WithContext(ctx)

	for i := 0; i < 5; i++ {
		eg.Go(func() (err error) {
			return somefuncWithCtx(ctx)
		})
	}
	err := eg.Wait()
	if err != nil {
		return  nil, err
	}

	eg1, ctx := errgroup.WithContext(ctx)
	for i := 0; i < 5; i++ {
		eg.Go(func() (err error) {
			return somefuncWithCtx(ctx)
		})
	}

	err = eg1.Wait()
	if err != nil {
		return  nil, err
	}

	return &Response{Message: "Hello, world!"}, nil
}

func somefuncWithCtx(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "https://google.com", nil)
	if err != nil {
		return err
	}
	_, err = http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	return nil
}
```

If you hit this endpoint, encore will crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13125a3]

goroutine 162 [running]:
encore.dev/runtime.httpCompleteRoundTrip(0xc0001f2100, 0x0, 0x15d6ca0, 0xc0000200d0)
	/usr/local/Cellar/encore/0.14.1/libexec/runtime/runtime/http.go:177 +0x4c3
net/http.encoreFinishRoundTrip(0xc0001f2100, 0x0, 0x15d6ca0, 0xc0000200d0)
	/usr/local/Cellar/encore/0.14.1/libexec/runtime/runtime/runtime.go:105 +0x49
net/http.(*Transport).roundTrip.func1(0xc000443a88, 0xc000443a90, 0xc000443a98)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/transport.go:511 +0x51
net/http.(*Transport).roundTrip(0x1878760, 0xc0001f2100, 0x0, 0x15d6ca0, 0xc0000200d0)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/transport.go:547 +0xf62
net/http.(*Transport).RoundTrip(0x1878760, 0xc0001f2100, 0x1878760, 0x0, 0x0)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0001f2100, 0x15d7780, 0x1878760, 0x0, 0x0, 0x0, 0xc000296020, 0x101a677, 0x1, 0x0)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0x187f860, 0xc0001f2100, 0x0, 0x0, 0x0, 0xc000296020, 0x0, 0x1, 0xc0001f2100)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0x187f860, 0xc0001f2100, 0x0, 0x0, 0x0)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	/usr/local/Cellar/encore/0.14.1/libexec/encore-go/src/net/http/client.go:585
encore.app/hello.somefuncWithCtx(0x15e1918, 0xc00041e3c0, 0x0, 0x0)
	/Users/matthewboyle/Dev/budgsey-api/hello/hello.go:49 +0x97
encore.app/hello.World.func2(0x0, 0x0)
	/Users/matthewboyle/Dev/budgsey-api/hello/hello.go:31 +0x36
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00029a240, 0xc0006288e0)
	/Users/matthewboyle/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/matthewboyle/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

Here is the same code "working" in a standard go context: https://play.golang.org/p/n0izzHq-Igt

I fixed this for now in my code by using the regular error group without context (context.Background() worked too) but of course I lose the ability to cancel and tracing then.

**Comment by eandre** [comment]
Thanks for the report and for the reproducer! I've fixed the issue and will tag `v0.14.2` shortly to fix it.

**Comment by MatthewJamesBoyle** [comment]
Thanks for the incredibly fast fix!

**Comment by eandre** [comment]
You're welcome :) it took a bit longer than expected due to the GitHub Actions outage, but you can install it now using `encore version update`.
