### ISSUE TITLE
encore run panic

### ISSUE THREAD

**Issue by fritzkeyzer** [encoredev/encore#921]
I can recreate this by having multiple package names defined in a directory

Go build output:
```
go build ./...
found packages pkg (package.go) and secondpkg (secondpkg.go) in repo/pkg
```

Encore output:
```
encore run

  ❌ Building Encore application graph... Failed: Error
  ⠒ Analyzing service topology...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x100cefe98]

goroutine 1 [running]:
encr.dev/pkg/errinsrc/internal.SrcLocations.GroupByFile({0x14000274178, 0x1, 0x140005ad678?})
	/Users/runner/work/encore/encore/encr.dev/pkg/errinsrc/internal/location.go:142 +0x98
encr.dev/pkg/errinsrc.(*ErrInSrc).Error(0x1400047e600)
	/Users/runner/work/encore/encore/encr.dev/pkg/errinsrc/errinsrc.go:189 +0x780
encr.dev/pkg/errlist.(*List).Error(0x140003604a0)
	/Users/runner/work/encore/encore/encr.dev/pkg/errlist/errlist.go:186 +0x10c
encr.dev/cli/cmd/encore/cmdutil.DisplayError(0x140002e7b60?, {0x14000252f00, 0x4f0, 0x500})
	/Users/runner/work/encore/encore/encr.dev/cli/cmd/encore/cmdutil/cmdutil.go:133 +0x140
main.displayError(...)
	/Users/runner/work/encore/encore/encr.dev/cli/cmd/encore/main.go:184
main.streamCommandOutput({0x12a3f1a38, 0x140002e7b60}, 0x140003b6460)
	/Users/runner/work/encore/encore/encr.dev/cli/cmd/encore/main.go:142 +0x5ec
main.runApp({0x14000044004, 0x17}, {0x101fdcc30, 0x1})
	/Users/runner/work/encore/encore/encr.dev/cli/cmd/encore/run.go:111 +0x4b0
main.init.12.func1(0x140001a7d00?, {0x103263060?, 0x4?, 0x101babd13?})
	/Users/runner/work/encore/encore/encr.dev/cli/cmd/encore/run.go:45 +0x24
github.com/spf13/cobra.(*Command).execute(0x14000347200, {0x103263060, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x103201a40)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/Users/runner/work/encore/encore/encr.dev/cli/cmd/encore/main.go:35 +0x180
```

**Comment by simon-johansson** [comment]
If you're looking to split your service into multiple packages, Encore supports this through sub-packages. You can structure your service like this:

```
/my-service
    encore.service.go   // service definition
    service.go          // main package code
    /subpkg
        helper.go       // sub-package with its own package name
```

The key rule is that sub-packages within a service can't define Encore APIs or other Encore primitives — those must live in the top-level service package. Sub-packages are great for internal helper code, types, utilities, etc.

More details here: https://encore.dev/docs/go/primitives/app-structure#structure-services-using-sub-packages
